all: comp1

comp1:
	g++ --std=c++11 _mainTester.cpp -o mainTester

comp2:
	g++ --std=c++11 myMain.cpp -o myMain

run0:
	./mainTester t1.txt 1 1

run1:
	./mainTester t1.txt 1 2

runmy0:
	./myMain t1.txt 1 1

runmy1:
	./myMain t1.txt 1 2

clean:
	rm mainTester

cleanmy:
	rm myMain
